apiVersion: v1
kind: Service
metadata:
  name: sample-api-service
spec:
  type: NodePort  # Using NodePort for local testing
  selector:
    app: sample-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # The application will be accessible on localhost:30080
